---
- hosts: "{{ host }}"
  gather_facts: false
  become: true
  
  tasks:
  - name: install needed network manager libs
    package:
      name:
        - NetworkManager-libnm
        - nm-connection-editor
        - libsemanage-python
        - policycoreutils-python
      state: present

  - name: Add an Ethernet connection with static IP configuration
    nmcli:
      conn_name: "{{ conn_name }}"
      ifname: eth1
      type: ethernet
      ip4: "{{ ip_addr }}/24"
      state: "{{ act }}"