---
- hosts: "{{ host }}"
  gather_facts: false
  become: true
  
  tasks:

  - name: Copy/backup file/directories with owner and permissions
    copy:
      src: "{{ source_path }}"
      dest: "{{ dest_path }}"
      owner: vagrant
      group: vagrant
      mode: '0644'
    when: backup_file | bool

  - name: Compress directory "{{ source_path }}" into "{{ dest_path }}"
    archive:
      path: "{{ source_path }}"
      dest: "{{ dest_path }}"
    when: backup_directory | bool

  - name: fetch/restore file/directory from backup server
    fetch:
      src: "{{ source_path }}"
      dest: "{{ dest_path }}"
    when: restore | bool