---
- hosts: "{{ host }}"
  gather_facts: false
  
  tasks:

  - name: Copy/backup file/directories with owner and permissions
    copy:
      src: "{{ source_path }}"
      dest: "{{ dest_path }}"
      owner: vagrant
      group: vagrant
      mode: '0644'
      backup: yes
    when: backup | bool

  - name: fetch/restore file/directory from backup server
    fetch:
      src: "{{ source_path }}"
      dest: "{{ dest_path }}"
    when: restore | bool