---
- hosts: "{{ host }}"
  gather_facts: false
  become: true
  
  tasks:
  - name: create a sub-interface config file
    template:
      src: "/tmp/ifcfg-eth1:1.j2"
      dest: "/etc/sysconfig/network-scripts/ifcfg-{{ interface }}"

  - name: make interface up
    command: "ifup {{ interface }}"
    