---
- hosts: "{{ host }}"
  gather_facts: false
  become: true
  
  tasks:
  - name: create a sub-interface config file
    copy:
      src: "/etc/sysconfig/network-scripts/ifcfg-{{ interface }}"
      dest: "/etc/sysconfig/network-scripts/ifcfg-{{ interface }}:1"
    delegate_to: localhost