---
- hosts: "{{ host }}"
  gather_facts: true

  tasks:
  - name: Set service startup mode to auto and ensure it is started
    win_service:
      name: "{{ service_name }}"
      start_mode: "{{ startup_type }}"
      state: "{{ startup_state }}"